### ISSUE TITLE
关于SMG模块的问题

### ISSUE THREAD

**Issue by warmpu** [winycg/HCGNet#1]
你好！作者的工作很棒！有个问题想请教下，
    x_shortcut_weight = self.global_pool(x_shortcut * forget_context_weight) * H * W
全局池化后维度应该是1X1XC，这里为啥要乘以H*W？

**Comment by winycg** [comment]
你好！H*W是一个常数（constant），global average pool实现了对spatial维度的平均，也就是÷(H*W)，因为forget_context_weight（Softmax归一化的权重）已经实现了对feature map的加权平均，所以需要*(H*W)来弥补÷(H*W)，谢谢你的关注！

**Comment by warmpu** [comment]
get了，谢谢回复！
